### ISSUE TITLE
httpx.RemoteProtocolError is not catched

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enochecker3#20]
https://github.com/ldruschk/enochecker3/blob/c97789ad33214be8a3995eb9dbc16847222b65af/enochecker3/enochecker.py#L305

is that intentional?

```
checker_1  | Traceback (most recent call last):
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
checker_1  |     yield
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 283, in handle_async_request
checker_1  |     ) = await self._pool.handle_async_request(
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
checker_1  |     response = await connection.handle_async_request(
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 148, in handle_async_request
checker_1  |     return await self.connection.handle_async_request(
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 128, in handle_async_request
checker_1  |     ) = await self._receive_response(timeout)
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 189, in _receive_response
checker_1  |     event = await self._receive_event(timeout)
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 236, in _receive_event
checker_1  |     raise RemoteProtocolError(msg)
checker_1  | httpcore.RemoteProtocolError: Server disconnected without sending a response.
checker_1  | 
checker_1  | The above exception was the direct cause of the following exception:
checker_1  | 
checker_1  | Traceback (most recent call last):
checker_1  |   File "/usr/local/lib/python3.9/site-packages/enochecker3/enochecker.py", line 500, in checker
checker_1  |     return await self._call_putflag(
checker_1  |   File "/usr/local/lib/python3.9/site-packages/enochecker3/enochecker.py", line 314, in _call_putflag
checker_1  |     attack_info: Optional[str] = await self._call_method(task)
checker_1  |   File "/usr/local/lib/python3.9/site-packages/enochecker3/enochecker.py", line 294, in _call_method
checker_1  |     return await asyncio.wait_for(
checker_1  |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
checker_1  |     return fut.result()
checker_1  |   File "/usr/local/lib/python3.9/site-packages/enochecker3/enochecker.py", line 290, in _call_method_raw
checker_1  |     return await f(*args)
checker_1  |   File "/checker/checker.py", line 82, in putflag_test
checker_1  |     await client0.register()
checker_1  |   File "/checker/client.py", line 148, in register
checker_1  |     reg_result = await self.http_client.post("/api/account/register", params={"username": self.username, "password": self.password})
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1807, in post
checker_1  |     return await self.request(
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1481, in request
checker_1  |     response = await self.send(
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1568, in send
checker_1  |     response = await self._send_handling_auth(
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1604, in _send_handling_auth
checker_1  |     response = await self._send_handling_redirects(
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1640, in _send_handling_redirects
checker_1  |     response = await self._send_single_request(request, timeout)
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1681, in _send_single_request
checker_1  |     ) = await transport.handle_async_request(
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 278, in handle_async_request
checker_1  |     (
checker_1  |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
checker_1  |     self.gen.throw(typ, value, traceback)
checker_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
checker_1  |     raise mapped_exc(message) from exc
checker_1  | httpx.RemoteProtocolError: Server disconnected without sending a response.
```

**Comment by ldruschk** [comment]
Should that be handled as Mumble or Offline? I would assume Mumble, since the connection is at least established

**Comment by Trolldemorted** [comment]
Good question, we could also consider it offline, since the docker proxy sends TCP ACKs back even if the containered service is not responding at all (?)
